name: Subscription Updater

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '*/2 * * * *'

jobs:
  update-vmess:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update vmess.txt
        run: |
          curl -o vmess.txt -LJO "https://raw.githubusercontent.com/yebekhe/TelegramV2rayCollector/main/sub/base64/vmess"
          git add vmess.txt
          git commit -m "🚀 Servers Updated - $(TZ='Asia/Tehran' date '+%Y-%m-%d %H:%M:%S') Asia/Tehran"
          git push
