name: Subscription Updater

on:
  schedule:
    - cron: '0 */2 * * *'  # Run every 2 hours

jobs:
  update-vmess:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update vmess.txt
        run: |
          curl -o vmess.txt https://google.com/raw/path/to/vmess.txt
          git add vmess.txt
          git commit -m "🚀 Servers Updated - $(TZ='Asia/Tehran' date '+%Y-%m-%d %H:%M:%S') Asia/Tehran"
          git push
